language: node_js

services:
  - couchdb

node_js:
  - "6"

sudo: false

before_install:
  # package-lock.json was introduced in npm@5
  - npm install -g npm@5 # skip this if you are using node 9
  - npm install -g greenkeeper-lockfile@1

before_script:
  # update package-lock.json
  - greenkeeper-lockfile-update
  # ensure correct CORS configuration of the couchdb service
  - npm install add-cors-to-couchdb
  - ./node_modules/.bin/add-cors-to-couchdb
  # run linter before the tests
  - npm run lint

after_script:
  # upload the updated package-lock.json
  - greenkeeper-lockfile-upload

script: npm run $COMMAND

env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - secure: "U7yqHtQrvzNob8YMh9iH34piyr4N0ZoX/G45VUuGlOoXe2gjhwHMAERRISZLtdzHawYu780SZ7g42HP2jsgwXqGGUmxLNMTFY44V19030Fn2QFEIZ30Ni/t0VRpvt1gwiAwRQJlVyKxS4B6qctf6HGm+hS2gQHnGuj4uX9WMZ8A="
  - secure: "LjHjFT855IQ66dfXDroe5fmsBNohyO7j5M0sEHOaNvtqnVYVAfMgwW3JpESXhXY0mEgSSKSOtCEGK2iqhsGL1ou4nYP0TarV/aKBjclNotMWcBI+VdgvooCtV4D2LCmFWqJ8agxZnmkeqX+VmnMieEttZAcagXslcNARq96m9v0="
  - secure: "UqQRT/Fn3cIHWXd9quN0mFD4BG8WeyxJKlghPXF+q3BZOeRyXe4FpG7RJBQohGHvJYzPY27Yi7mIlEOLCICFtC0Os/qNueK11/D+J6Zhr8rPqi/JTUJth0ybwhSBXyb6Vfm4Ce4m8hfKfLHTbo5FP533RuIUhPrThO3+APpxdCo="

  matrix:
  - CLIENT=node COMMAND=test
  - CLIENT=phantom COMMAND=test
  - CLIENT=saucelabs:Chrome COMMAND=test
  - CLIENT=saucelabs:Firefox COMMAND=test
  - CLIENT=saucelabs:Safari:7 COMMAND=test
  - CLIENT="saucelabs:Internet Explorer:10:Windows 8" COMMAND=test
  - CLIENT="saucelabs:Internet Explorer:11:Windows 10" COMMAND=test

matrix:
  allow_failures:
    # Waiting for pouchdb/pouchdb#6814
    - env: CLIENT=node COMMAND=test
    # Waiting for pouchdb/pouchdb#6855
    - env: CLIENT="saucelabs:Internet Explorer:11:Windows 10" COMMAND=test

branches:
  only:
  - master
  - /^greenkeeper/.*$/
